### PR TITLE
Update `Kiwisolver` to version `1.3.2`

### PR DESCRIPTION
**Pull request by varlackc**
`kiwisolver` version `1.3.2`
1. - [x] check the upstream
    https://github.com/nucleic/kiwi/tree/1.3.2

2. - [x] check the pinnings

    https://github.com/nucleic/kiwi/blob/1.3.2/setup.py

    minimum supported version of python is `python` `3.7`

    https://github.com/nucleic/kiwi/blob/1.3.2/setup.py#L90

3. - [x] check the changelogs

    https://github.com/nucleic/kiwi/blob/1.3.2/releasenotes.rst

    `python` version `3.6` and older are no longer supported
    `python` version `3.10` is now supported

    Direct asses to `ob_type` in `C-API` has been removed, it is recommended to use `Py_TYPE` instead

4. - [x] additional research
    https://github.com/conda-forge/kiwisolver-feedstock/issues

    At the time of the review there are no open issues mentioned in conda forge

5. - [x] verify dev_url
    https://github.com/nucleic/kiwi

6. - [x] verify doc_url
    https://pypi.python.org/pypi/kiwisolver

7. - [x] license is spdx compliant
    https://spdx.org/licenses/BSD-3-Clause.html
8. - [x] license family
    https://spdx.org/licenses/BSD-3-Clause.html
    (BSD)
9. - [x] verify the build number
    The build number is set to zero
10. - [x] verify setuptools
    Setuptools is in the recipe
11. - [x] verify wheel
    Wheel is in the recipe
12. - [x] pip in the test section
13. - [x] veriy the test section

Results:
- All Passed

Based on the research findings and the results we can conclude
that it is safe to update `kiwisolver` to version `1.3.2`

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
The description is about `jedi` but it should be `kiwisolver`

**Comment by skupr-anaconda** [comment]
It's unuseful line https://github.com/AnacondaRecipes/kiwisolver-feedstock/blob/0e54a14cbbdee5f4df685de62848983120bcaf97/recipe/meta.yaml#L36 if the package is architecture specific

And for **not** noarch packages it's enough to use `skip: True [py<37]` without constraint in run https://github.com/AnacondaRecipes/kiwisolver-feedstock/blob/0e54a14cbbdee5f4df685de62848983120bcaf97/recipe/meta.yaml#L29, see https://github.com/anaconda-distribution/distro-handbook/blob/main/source/package_review.rst#decision-making-process-to-update-the-recipe

**Comment by varlackc** [comment]
> The description is about `jedi` but it should be `kiwisolver`

Sorry for the confusion, the correct notes are now added

**Comment by varlackc** [comment]
> It's unuseful line
> 
> https://github.com/AnacondaRecipes/kiwisolver-feedstock/blob/0e54a14cbbdee5f4df685de62848983120bcaf97/recipe/meta.yaml#L36
> 
> if the package is architecture specific
> And for **not** noarch packages it's enough to use `skip: True [py<37]` without constraint in run
> 
> https://github.com/AnacondaRecipes/kiwisolver-feedstock/blob/0e54a14cbbdee5f4df685de62848983120bcaf97/recipe/meta.yaml#L29
> 
> , see https://github.com/anaconda-distribution/distro-handbook/blob/main/source/package_review.rst#decision-making-process-to-update-the-recipe

The unhelpful lines were removed

**Review by skupr-anaconda — APPROVED** [review]

**Review by chenghlee — APPROVED** [review]

**Review by chenghlee — CHANGES_REQUESTED** [review]
Wait, why are we updating again? Wasn't that done in in PR #3?

**Comment by varlackc** [comment]
> Wait, why are we updating again? Wasn't that done in in PR #3?

There were some improvements that could be made to the recipe, but probably we should add the improvements on the next version.

**Pull request closed without merging**
