### PR TITLE
kiwisolver 1.4.4

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Jira ticket:** [PKG-947](https://anaconda.atlassian.net/browse/PKG-947)

**The upstream data:**
Changes: https://github.com/nucleic/kiwi/releases
License: https://github.com/nucleic/kiwi/blob/1.4.4/LICENSE
Requirements: 
- setup.py https://github.com/nucleic/kiwi/blob/1.4.4/setup.py
- pyproject.toml https://github.com/nucleic/kiwi/blob/1.4.4/pyproject.toml

**_Actions:_**

- Add more jinja2 templates

- Remove pinnings from host

- Fix doc_url

**Additional info:**

<details>

**Package's statistics**

<details>

 * Priority C | effort: easy | Category: anaconda | subcategory:  | pkg_type: python
 * Outdated platfroms: 'linux-64', 'linux-aarch64', 'linux-s390x', 'linux-ppc64le', 'osx-64', 'osx-arm64', 'win-64'
 * Latest version: 1.4.4
 * Release on PyPi:
    * version: 1.4.4
    * date: 2022-07-15T20:38:00
* [PyPi history](https://pypi.org/project/kiwisolver/#history)
 * Popularity: 
    * 3 months downloads: 2906354.0
    * All time:  19549268 downloads -  kiwisolver  1.4.4  A fast implementation of the Cassowary constraint solver  

</details>

**Other checks:**

<details>

1. - [x] https://github.com/nucleic/kiwi/tree/1.4.4 exists
3. - [x] Check the pinnings
8. - [x] Verify that the `build_number` is correct
9. - [x] Verify if the package needs `setuptools`
10. - [x] has `wheel`
11. - [x] `pip` in test
12. - [x] Verify the test section
13. - [x] Verify if the package is `architecture specific`
14. - [x] Verify that private modules are not mentioned in the recipe For example: (_private_module)
15.  - [x] license_file: LICENSE is present
16. - [x] license_family BSD is present
17. - [x] License: BSD-3-Clause
    - [x] License is `spdx` compliant
 * Check if the license identifier has correct name from the SPDX License List

| Identifier                           |
|:-------------------------------------|
| BSD-3-Clause                         |
| BSD-3-Clause-Attribution             |
| BSD-3-Clause-Clear                   |
| BSD-3-Clause-LBNL                    |
| BSD-3-Clause-Modification            |
| BSD-3-Clause-No-Military-License     |
| BSD-3-Clause-No-Nuclear-License      |
| BSD-3-Clause-No-Nuclear-License-2014 |
| BSD-3-Clause-No-Nuclear-Warranty     |
| BSD-3-Clause-Open-MPI                |
</details>

**Check dependency issues:**

<details>
../aggregate/kiwisolver-feedstock/recipe/meta.yaml
Dependencies: ['setuptools-scm >=3.4.3', 'toml', 'cppy >=1.2.0', 'pip', 'setuptools >=61.2', 'python', 'wheel']

noarch:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-ppc64le:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-s390x:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

osx-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

osx-arm64:
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

win-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

</details>

**Package Build Score: 19**

**Links:**
* [Anaconda Recipes feedstock](https://github.com/AnacondaRecipes/kiwisolver-feedstock)
* [Update branch](https://github.com/AnacondaRecipes/kiwisolver-feedstock/tree/1.4.4)
* [conda-forge recipe](https://github.com/{upstream}/{feedstock_name}-feedstock)
* [PyPI](https://pypi.org/project/kiwisolver)
* [Diff between upstream and feature branch](https://github.com/conda-forge/kiwisolver-feedstock/compare/main...AnacondaRecipes:1.4.4)
* [Diff between origin and feature branch](https://github.com/AnacondaRecipes/kiwisolver-feedstock/compare/master...AnacondaRecipes:1.4.4)
* [The last merged PRs](https://github.com/AnacondaRecipes/kiwisolver-feedstock/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc+)

</details>

**Updating the recipe:**
If the recipe needs additional modification the update branch can be modified. Note that the PR diffs are not updated with these changes.
```
git clone -b 1.4.4 git@github.com:AnacondaRecipes/kiwisolver-feedstock.git
```

### CODE REVIEW

**Comment by Jrice1317** [comment]
Not sure if both the `doc_url` and `doc_source_url` should be present, but other than that, LGTM!

**Review by Jrice1317 — COMMENTED** [review]
Not sure if both the doc_url and doc_source_url should be present, but other than that, LGTM!

**Review by psteyer — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
> Not sure if both the `doc_url` and `doc_source_url` should be present, but other than that, LGTM!

Thanks. I've removed doc_source_url

**Pull request merged**
